# Generated by Django 5.1.3 on 2024-11-12 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_alter_attendance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
