# Generated by Django 5.1.3 on 2024-11-12 05:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'Leave'), ('permission', 'Permission')], max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('hours_requested', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance_app.user')),
            ],
        ),
    ]
